import { openWhenLetters } from './openWhenLetters';

// Published IDs are explicit and must never be reassigned.
export const libraryNotePlacements = [
  { noteId: 'quiet-company', id: 1001, tone: 'soft' },
  { noteId: 'blanket-shaped-day', id: 1002, tone: 'soft' },
  { noteId: 'borrowed-heart', id: 1003, tone: 'soft' },
  { noteId: 'nothing-to-earn', id: 1004, tone: 'romantic' },
  { noteId: 'known-by-sloth', id: 1005, tone: 'romantic' },
  { noteId: 'forest-window', id: 1006, tone: 'soft' },
  { noteId: 'suspiciously-tiny-quest', id: 1007, tone: 'boost' },
  { noteId: 'next-inch', id: 1008, tone: 'boost' },
  { noteId: 'rest-is-an-action', id: 1009, tone: 'soft' },
  { noteId: 'quiet-version', id: 1010, tone: 'soft' },
  { noteId: 'feel-far-away', id: 1011, tone: 'romantic' },
  { noteId: 'nothing-for-anybody', id: 1012, tone: 'soft' },
  { noteId: 'day-was-a-lot', id: 1013, tone: 'romantic' },
  { noteId: 'quiet-afternoon', id: 1014, tone: 'soft' },
  { noteId: 'sad-without-reason', id: 1015, tone: 'soft' },
  { noteId: 'five-minutes-outside', id: 1016, tone: 'soft' },
  { noteId: 'company-no-interaction', id: 1017, tone: 'soft' },
  { noteId: 'nighttime-strange', id: 1018, tone: 'romantic' },
  { noteId: 'smallest-hug', id: 1019, tone: 'romantic' },
  { noteId: 'stay-softly', id: 1020, tone: 'soft' },
  { noteId: 'couch-calling', id: 1021, tone: 'silly' },
  { noteId: 'safe-little-room', id: 1022, tone: 'soft' },
  { noteId: 'afraid-too-much', id: 1023, tone: 'romantic' },
  { noteId: 'say-nothing', id: 1024, tone: 'soft' },
  { noteId: 'stop-for-a-bit', id: 1025, tone: 'soft' },
  { noteId: 'all-you-can-do-exist', id: 1026, tone: 'romantic' },
  { noteId: 'know-you-by-heart', id: 1027, tone: 'romantic' },
  { noteId: 'bad-day-still-us', id: 1028, tone: 'romantic' },
  { noteId: 'mouse-trivia', id: 1029, tone: 'romantic' },
  { noteId: 'holding-my-end', id: 1030, tone: 'romantic' },
  { noteId: 'this-mouse-too', id: 1031, tone: 'romantic' },
  { noteId: 'no-report-card', id: 1032, tone: 'romantic' },
  { noteId: 'quiet-not-forgotten', id: 1033, tone: 'romantic' },
  { noteId: 'carry-the-sparkle', id: 1034, tone: 'romantic' },
  { noteId: 'remember-your-pieces', id: 1035, tone: 'soft' },
  { noteId: 'final-answer-love', id: 1036, tone: 'romantic' },
  { noteId: 'mouse-sized-cafe', id: 1037, tone: 'silly' },
  { noteId: 'five-second-vacation', id: 1038, tone: 'soft' },
  { noteId: 'aquarium-break', id: 1039, tone: 'soft' },
  { noteId: 'somewhere-else', id: 1040, tone: 'soft' },
  { noteId: 'cozy-soundscape', id: 1041, tone: 'soft' },
  { noteId: 'five-minute-universe', id: 1042, tone: 'boost' },
  { noteId: 'soft-thing-assignment', id: 1043, tone: 'boost' },
  { noteId: 'mouse-nest', id: 1044, tone: 'soft' },
  { noteId: 'curtain-choice', id: 1045, tone: 'boost' },
  { noteId: 'heart-signal', id: 1046, tone: 'romantic' },
  { noteId: 'comfier-paw', id: 1047, tone: 'silly' },
  { noteId: 'one-color', id: 1048, tone: 'boost' },
  { noteId: 'closest-comfort-wins', id: 1049, tone: 'soft' },
  { noteId: 'move-one-thing', id: 1050, tone: 'boost' },
  { noteId: 'slightly-different', id: 1051, tone: 'boost' },
  { noteId: 'fresh-air-choice', id: 1052, tone: 'soft' },
  { noteId: 'free-the-mouse', id: 1053, tone: 'silly' },
  { noteId: 'room-two-percent', id: 1054, tone: 'boost' },
  { noteId: 'tiny-comfort-menu', id: 1055, tone: 'soft' },
  { noteId: 'comfortable-clothes', id: 1056, tone: 'silly' },
  { noteId: 'past-the-phone', id: 1057, tone: 'boost' },
  { noteId: 'acceptable-food', id: 1058, tone: 'soft' },
  { noteId: 'point-one-percent', id: 1059, tone: 'boost' },
  { noteId: 'tiny-paw-delivery', id: 1060, tone: 'romantic' },
  { noteId: 'one-tab-not-now', id: 1061, tone: 'boost' },
  { noteId: 'one-sound', id: 1062, tone: 'soft' },
  { noteId: 'one-tiny-comfort', id: 1063, tone: 'soft' },
  { noteId: 'five-second-rest', id: 1064, tone: 'soft' },
  { noteId: 'category-five', id: 1065, tone: 'silly' },
  { noteId: 'suspend-even', id: 1066, tone: 'silly' },
  { noteId: 'independent-love-review', id: 1067, tone: 'romantic' },
  { noteId: 'choose-supervisor', id: 1068, tone: 'silly' },
  { noteId: 'sunset-delivery', id: 1069, tone: 'soft' },
  { noteId: 'smallest-cinema', id: 1070, tone: 'silly' },
  { noteId: 'slothtech-startup', id: 1071, tone: 'silly' },
  { noteId: 'suspicious-squeaking', id: 1072, tone: 'silly' },
] as const;

export const pileNoteIds = new Set([
  'cloud-tour',
  'sloth-support-ticket',
  'dont-want-to-explain',
  'world-too-loud',
  'blanket-lumps',
  'hand-under-table',
  'incognito-mouse',
  'borrow-my-lap',
  'not-mouse-ish',
  'miss-stupid-face',
  'tiny-smirk',
  'what-sloth-sees',
  'mouse-certificate',
  'future-sloth',
  'choose-you',
  'tiny-love-list',
  'our-weird-museum',
  'my-cuchis',
  'the-maccuties',
  'home-to-sloth',
  'pocket-love-letter',
  'you-contribute-home',
  'unlimited-kisses',
  'tiny-weather',
  'cloud-inspection',
  'quiet-train-ride',
  'tiny-museum',
  'sloth-pockets',
  'harlito-field-trip',
  'tiny-island',
  'nice-patch-of-light',
  'woodland-gossip',
  'planet-mouse',
  'blueberry-mystery',
  'slow-chase',
  'duck-pants',
  'creature-parade',
  'tiny-garden',
  'theodore-teaspoon',
  'another-channel',
  'hydration-pause',
  'choose-nothing-menu',
  'warm-thing',
  'horizontal-permission',
  'tiniest-mouse-plan',
  'chief-tiny-promotion',
  'blanket-apology',
  'woodland-court-session',
  'woodland-committee',
  'mouse-horoscope',
  'cozy-front',
  'hr-cuteness',
  'golden-acorn-award',
  'forehead-kiss-complaint',
  'harlito-command',
  'mouse-performance-review',
  'good-enough-memo',
  'missing-mouse-found',
  'snack-negotiations',
  'blanket-science',
  'sloth-espionage',
  'neighborhood-watch',
  'affection-package',
  'sloth-mouse-review',
  'top-secret-mouse',
  'official-investigation',
  'person-excessive',
  'need-me-no-idea',
  'low-power-mode',
  'productivity-report',
  'guilt-submission-denied',
  'original-weirdness',
  'sleepy-red-panda',
  'cozy-window-backstories',
  'acorn-siren',
  'acorn-economy',
  'mouse-law',
]);

const costs = { soft: 30, silly: 40, boost: 60, romantic: 80 };
export const transferredMessages = libraryNotePlacements.map(placement => {
  const note = openWhenLetters.find(note => note.id === placement.noteId)!;
  return { id: placement.id, tone: placement.tone, title: note.title, text: [...note.message, note.closing].join('\n\n'), tag: placement.tone, cost: costs[placement.tone] };
});
