export type CompanyNeed = {
  id: string;
  label: string;
  emoji: string;
  description: string;
};

export type OpenWhenLetter = {
  id: string;
  needs: string[];
  title: string;
  message: string[];
  closing: string;
  artwork?: { src: string; alt: string };
};

// CONTENT WORKSHOP
// To add care for a new feeling, add one option here and use its id on letters below.
export const companyNeeds: CompanyNeed[] = [
  { id: 'sit-with-me', label: 'Sit with me', emoji: '🫂', description: 'Quiet company. No fixing.' },
  { id: 'remind-me', label: "Remind me I'm loved", emoji: '💜', description: 'Something true to hold onto.' },
  { id: 'distract-me', label: 'Distract me gently', emoji: '🌤️', description: 'A tiny change of scenery.' },
  { id: 'make-me-laugh', label: 'Make me laugh', emoji: '🐭', description: 'Low-stakes woodland nonsense.' },
  { id: 'tiny-thing', label: 'One tiny thing', emoji: '🌱', description: 'The smallest possible next move.' },
];

// Add a letter by copying one block. IDs must be unique; `needs` controls where it appears.
// Messages are arrays so each short paragraph is easy to edit without HTML.
export const openWhenLetters: OpenWhenLetter[] = [
  {
    id: 'quiet-company', needs: ['sit-with-me'], title: 'when words are too much',
    message: ["You don't have to tell me what hurts. I can just be your quiet sloth for a while."],
    closing: 'No fixing. Just us. 💜',
  },
  {
    id: 'blanket-shaped-day', needs: ['sit-with-me', 'remind-me'], title: 'for a blanket-shaped day',
    message: ['You do not need to turn today around. Come be a bundled little mouse while I keep watch.'],
    closing: 'Loved exactly as you are. 🦥',
  },
  {
    id: 'borrowed-heart', needs: ['sit-with-me', 'remind-me'], title: 'borrow my heart for a minute',
    message: ['If your thoughts are not being gentle, borrow mine: you are precious, wanted, and never a burden.'],
    closing: 'I have enough belief for both of us. 💌',
  },
  {
    id: 'nothing-to-earn', needs: ['remind-me'], title: 'nothing to earn',
    message: ['You do not have to be cheerful, useful, or okay for me. You are still my favorite mouse.'],
    closing: 'Loved on the bright days. Loved on this one too. 💜',
  },
  {
    id: 'known-by-sloth', needs: ['remind-me'], title: 'in case your brain forgot',
    message: ['I know your softness, your ridiculous humor, and how hard you try. A foggy brain cannot erase that.'],
    closing: 'Sloth remembers. 🦥✨',
  },
  {
    id: 'cloud-tour', needs: ['distract-me'], title: 'a very small cloud tour',
    message: ['One round cloud packed a grape, clean socks, and absolutely no itinerary. It is thriving.'],
    closing: 'You may drift beside it. ☁️',
  },
  {
    id: 'forest-window', needs: ['distract-me', 'sit-with-me'], title: 'look through this tiny window',
    message: ['Soft rain. One sleepy lamp. A mouse-sized mug warming both paws. No clocks.'],
    closing: 'This little window stays open. 🌧️',
  },
  {
    id: 'official-investigation', needs: ['make-me-laugh'], title: 'an official investigation',
    message: ['The woodland council found Mouse illegally adorable. Sloth volunteered to supervise the suspect.'],
    closing: 'Many kisses pending. 🕵️🐭',
  },
  {
    id: 'sloth-support-ticket', needs: ['make-me-laugh', 'distract-me'], title: 'support ticket #0001',
    message: ['Issue: today is extremely today-shaped. Proposed fix: one snack and two forehead kisses.'],
    closing: 'Escalated to the Blanket Department. 📋',
  },
  {
    id: 'suspiciously-tiny-quest',  needs: ['tiny-thing'], title: 'a suspiciously tiny quest',
    message: ['Choose one: take a sip, loosen your shoulders, or put both feet somewhere soft. That is the whole quest.'],
    closing: 'Doing none costs you zero love. 🌱',
  },
  {
    id: 'next-inch', needs: ['tiny-thing'], title: 'only the next inch',
    message: ['The whole day is too large. What could make the next five minutes one percent kinder?'],
    closing: 'Tiny counts. Pausing also counts. 🐾',
  },
  {
    id: 'rest-is-an-action',  needs: ['tiny-thing', 'sit-with-me'], title: 'rest is an action too',
    message: ['Closing your eyes or putting the phone down can be the next kind thing. You may stop here.'],
    closing: 'Sloth will keep your place. 💤',
  },
  { id: 'dont-want-to-explain', artwork: {"src": "./open-when/nearby-creature.jpg", "alt": "Sloth sits beside Mouse wearing a Nearby Creature badge."}, needs: ['sit-with-me', 'remind-me'], title: "when you don't want to explain", message: ['No tienes que decir nada hoy. Tu Slothy aquí está, assuming the official position of Nearby Creature and asking exactly zero questions.'], closing: 'Quiet Mouse is still my Mouse. 💜🩵' },
  { id: 'world-too-loud', artwork: {"src": "./open-when/quiet-world.jpg", "alt": "Mouse and Sloth cuddle under a blanket beside a softly lit window."}, needs: ['sit-with-me', 'distract-me'], title: 'when everything feels too loud', message: ['Imagine I turned the whole world down to 12%. Curtains closed. Gentle rain somewhere outside. Your feet under my leg. Nothing else is happening.'], closing: 'Stay here with me a little. 🧡' },
  { id: 'quiet-version',  needs: ['sit-with-me'], title: 'when you need the quiet version of me', message: ['No pep talk. No questions. Just my paw next to yours.'], closing: "Hi. I'm here. 🐾" },
  { id: 'blanket-lumps', artwork: {"src": "./open-when/two-blanket-lumps.jpg", "alt": "Two mysterious blanket lumps on a cozy couch."}, needs: ['sit-with-me', 'make-me-laugh'], title: 'when you want to disappear under a blanket', message: ['Approved. I’m coming too. We can be two mysterious blanket lumps until further notice.'], closing: 'Love, the larger lump. 💜' },
  { id: 'feel-far-away', needs: ['sit-with-me', 'remind-me'], title: 'when you feel far away', message: ['You don’t have to cross the whole distance back to me. I can sit with you from here.'], closing: 'No traveling required, Cuchis. 🩵' },
  { id: 'nothing-for-anybody',  needs: ['sit-with-me', 'tiny-thing'], title: 'when you have nothing for anybody', message: ['Then nobody gets anything today. Not even me.'], closing: 'Just be my sleepy little Mouse. 😴' },
  { id: 'category-five', needs: ['sit-with-me', 'make-me-laugh'], title: 'when your brain is a category-five hurricane', message: ['Sloth brought her raincoat. I have no idea how to control the weather, but we don’t have to solve that tonight.'], closing: 'Your underqualified meteorologist assistant. ⛈️' },
  { id: 'hand-under-table', artwork: {"src": "./open-when/paw-under-the-table.jpg", "alt": "Sloth and Mouse hold paws under a table with two warm mugs."}, needs: ['sit-with-me'], title: 'when you need a hand under the table', message: ['My hand finds yours under the table. One little squeeze. That’s the whole conversation.'], closing: 'Squeeze squeeze. 🧡' },
  { id: 'day-was-a-lot', needs: ['sit-with-me', 'remind-me'], title: 'when today has been a lot', message: ['Come home. Not the house—the little place that happens when it’s you and me.'], closing: 'You’re my favorite home. 🏡' },
  { id: 'incognito-mouse', artwork: {"src": "./open-when/cozy-incognito-mode.jpg", "alt": "Mouse hides under a blanket while Sloth keeps quiet company."}, needs: ['sit-with-me', 'make-me-laugh'], title: 'when you’re tired of existing', message: ['Incognito Mouse mode activated. I perceive only one Mouse-shaped blanket bump.'], closing: 'No further data collected. 🤫' },
  { id: 'quiet-afternoon', needs: ['sit-with-me', 'distract-me'], title: 'when you need a quiet afternoon', message: ['Rain on the window. Something warm nearby. You tucked against me. Nothing else required.'], closing: 'Just rain, Mouse, Sloth. 🧡' },
  { id: 'suspend-even', needs: ['sit-with-me', 'make-me-laugh'], title: 'when you can’t even', message: ['Then don’t even. Sloth hereby suspends Even until tomorrow.'], closing: 'Come be an Odd with me. 🙃' },
  { id: 'borrow-my-lap', artwork: {"src": "./open-when/my-lap.jpg", "alt": "Sleepy Mouse rests on Sloth’s lap on the couch."}, needs: ['sit-with-me', 'remind-me'], title: 'when you need to borrow my lap', message: ['Mouse head goes here. Sloth hand goes on head. The best cuchicuchi may occur.'], closing: 'Your reservation never expires. 💜' },
  { id: 'sad-without-reason', needs: ['sit-with-me'], title: 'when you’re sad but don’t know why', message: ['You don’t need a reason that makes sense. Sad can sit here too.'], closing: 'Scoot over Sad, Sloth is coming. 🦥' },
  { id: 'five-minutes-outside', needs: ['sit-with-me', 'tiny-thing'], title: 'when you need five minutes outside time', message: ['No messages. No plans. No explaining. Just couch, Mouse, Sloth, blanket.'], closing: 'The world can wait outside. 🚪' },
  { id: 'not-mouse-ish', artwork: {"src": "./open-when/flashlight-home.jpg", "alt": "Sloth waits at a warmly lit doorway with a flashlight for Mouse."}, needs: ['sit-with-me', 'remind-me'], title: 'when you don’t feel very Mouse-ish', message: ['Está bien. I know where Mouse lives even when Mouse can’t find him.'], closing: 'I’ll keep a flashlight nearby just in case. 🔦' },
  { id: 'company-no-interaction',  needs: ['sit-with-me', 'tiny-thing'], title: 'when you need company but not interaction', message: ['Perfect. I’ll sit nearby. You can nap, scroll, stare, or become furniture.'], closing: 'Maximum company. Minimum requirements. 🧡' },
  { id: 'nighttime-strange', needs: ['sit-with-me', 'remind-me'], title: 'when nighttime feels strange', message: ['Imagine sleepy Sloth beside you, one paw searching around until—ah. Found Mouse.'], closing: 'Nighty night, mi Cuchis. 💜' },
  { id: 'smallest-hug', needs: ['sit-with-me', 'tiny-thing'], title: 'when you need the smallest hug', message: ['Sloth leans one inch toward Mouse until our shoulders touch.'], closing: 'Tiny hug delivered. 💖' },
  { id: 'person-excessive', needs: ['sit-with-me', 'make-me-laugh'], title: 'when being a person seems excessive', message: ['Agreed. You may downgrade to woodland creature. Woodland creatures mostly sit in moss.'], closing: 'I’ll meet you there. 🦥🐭🌳' },
  { id: 'need-me-no-idea', needs: ['sit-with-me', 'make-me-laugh'], title: 'when you need me but don’t know what you need', message: ['Needing Sloth is sufficient paperwork. No supporting documents required.'], closing: 'Request approved forever. 💜♾️' },
  { id: 'stay-softly', needs: ['sit-with-me', 'remind-me'], title: 'when you want someone to stay', message: ['I can stay softly. No filling the silence. No needing anything back.'], closing: 'I know how to love you quietly too. 🤐' },
  { id: 'low-power-mode',  needs: ['sit-with-me', 'make-me-laugh'], title: 'when you’re running on 2%', message: ['Mouse has entered Low Power Mode. Blanket applied. Apps closed.'], closing: 'Nothing needs to run right now. 🪫' },
  { id: 'couch-calling', needs: ['sit-with-me', 'tiny-thing'], title: 'when the couch is calling', message: ['It says, “Hello Mouse. I have prepared a horizontal position and no agenda.”'], closing: 'Come squish in. 🛋️' },
  { id: 'safe-little-room', needs: ['sit-with-me', 'distract-me'], title: 'when you need a safe little room', message: ['Soft lamp. Cool sheets. No clocks. Mouse gets the good pillow.'], closing: 'This room is always yours. 🐭' },
  { id: 'afraid-too-much', needs: ['sit-with-me', 'remind-me'], title: 'when you’re afraid you’re too much', message: ['You’re not a burden I’m carrying. You’re my person. Sometimes my person hurts.'], closing: 'I still want you right here. 💜🤕🩵' },
  { id: 'say-nothing', needs: ['sit-with-me'], title: 'when you want to say nothing', message: ['Sloth sits next to Mouse. Paw on paw. No words.'], closing: '🐾💜🐾' },
  { id: 'stop-for-a-bit',  needs: ['sit-with-me', 'tiny-thing'], title: 'when you need to stop for a bit', message: ['Stop here. You don’t have to use the pause wisely or come back refreshed.'], closing: 'I’ll sit in it with you. Forever. 🛑' },
  { id: 'miss-stupid-face', needs: ['sit-with-me', 'distract-me'], title: 'when you miss my stupid face', message: ['Imagine Sloth peeking around the doorway in pink glasses. Found Mouse. Tiny smile. Retreat.'], closing: 'Found my favorite. 🤓' },
  { id: 'all-you-can-do-exist', needs: ['sit-with-me', 'remind-me'], title: 'when all you can do is exist', message: ['Conveniently, existing beside you is one of my favorite activities.'], closing: 'Professionally existing together. 🧡' },

  // Remind me I’m loved — Mouse’s author-provided notes.
  {"id": "misplaced-evidence",  "needs": ["remind-me", "make-me-laugh"], "title": "when your brain misplaced the evidence", "message": ["Evidence A: I still look for you when something funny happens. Evidence B: home keeps having you in it."], "closing": "Case extremely closed. 🧑🏻‍⚖️"},
  {"id": "productivity-report", "needs": ["remind-me", "make-me-laugh"], "title": "when you did absolutely nothing today", "message": ["Fascinating update: I remain wildly in love with you. Apparently love did not request your productivity report."], "closing": "Permanent policy. 📰"},
  {"id": "know-you-by-heart", "needs": ["remind-me", "sit-with-me"], "title": "when you feel faraway", "message": ["I don’t need you to perform Cuchis so I can remember who you are."], "closing": "I know you by heart. 💜"},
  {"id": "tiny-smirk", "needs": ["remind-me"], "title": "when you need one specific reason", "message": ["I love that tiny smirk you make when someone genuinely gets you."], "closing": "That face. My favorite. 😏"},
  {"id": "guilt-submission-denied", "needs": ["remind-me", "make-me-laugh"], "title": "when guilt is being a little bitch", "message": ["Guilt submitted 47 pages explaining why Mouse should feel bad. Sloth shredded them."], "closing": "Submission denied. 🚮"},
  {"id": "what-sloth-sees", "artwork": {"src": "./open-when/evidence-board-mouse-adored.jpg", "alt": "Detective Sloth shows Mouse a board of evidence that Mouse is adored."}, "needs": ["remind-me"], "title": "when you forget what I see", "message": ["Your softness. Your weird humor. Your brain. Your tinily strong Mouse opinions."], "closing": "I always see _you_, mi Cuchis. 🩵"},
  {"id": "mouse-certificate", "needs": ["remind-me", "make-me-laugh"], "title": "when you need your Mouse certificate", "message": ["CERTIFICATE OF MOUSE EXCELLENCE. Requirement: be this Mouse.", "Renewal: never."], "closing": "Signed, Not Biased Sloth. 📃"},
  {"id": "bad-day-still-us", "needs": ["remind-me", "sit-with-me"], "title": "when you think a bad day changed something", "message": ["Bad days change energy and plans. They don’t rewrite you, me, us."], "closing": "Still you 🩵. Still me 💜. Still us. 🧡"},
  {"id": "future-sloth", artwork: {"src": "./open-when/older-sloth-writing.jpg", "alt": "Older Sloth writes a love note at a cozy desk in the year 2060."}, "needs": ["remind-me", "distract-me"], "title": "when you need future Sloth", "message": ["Hi from Future Sloth. It’s a random Tuesday and I’m still stupidly happy you’re mine."], "closing": "Anyway. We’re cute. 🫣"},
  {"id": "mouse-trivia", "needs": ["remind-me", "make-me-laugh"], "title": "when you feel forgettable", "message": ["Impossible. My brain contains far too much Mouse trivia."], "closing": "You’ve fully colonized the premises. 🏳️"},
  {"id": "choose-you", "needs": ["remind-me"], "title": "when you wonder if I still choose you", "message": ["I choose you in boring little places: the couch spot, CVS, the dumb joke, the random thing I turn to tell you."], "closing": "I choo-choo chose you. 🚂"},
  {"id": "independent-love-review", "needs": ["remind-me", "make-me-laugh"], "title": "when you don’t feel lovable", "message": ["Independent review: still very in love with Mouse."], "closing": "Luckily my affection did not ask permission. 💜"},
  {"id": "tiny-love-list", "needs": ["remind-me"], "title": "when you need the tiny list", "message": ["Sleepy face. Tiny paws. Weird humor. Mouse opinions. That laugh when I really get you."], "closing": "Tiny list. Big love. 🦥💜🩵"},
  {"id": "holding-my-end", "needs": ["remind-me", "sit-with-me"], "title": "when you feel disconnected from us", "message": ["You don’t have to feel the thread for it to still be there. I’m holding my end."], "closing": "🦥〰️🐭"},
  {"id": "this-mouse-too", "needs": ["remind-me", "sit-with-me"], "title": "when you’re worried I miss the old you", "message": ["I miss easier times sometimes. I’m not waiting for an old Mouse to come back so I can love him."], "closing": "I love this Mouse too. 💜"},
  {"id": "our-weird-museum", "needs": ["remind-me", "distract-me"], "title": "when you need proof from the archives", "message": ["Silly jokes. Looks across rooms. Trips. Couch time. Podcasts. Coffee time. A thousand tiny pieces of us."], "closing": "I like our weird little museum. 🧡"},
  {"id": "no-report-card", "needs": ["remind-me", "sit-with-me"], "title": "when you think you’re disappointing me", "message": ["Mouse, you’re not an assignment. No secret rubric. No lost points."], "closing": "Put down the imaginary report card. 🐭💯"},
  {"id": "my-cuchis", "needs": ["remind-me"], "title": "when you need a very serious fact", "message": ["Sometimes I look at you doing nothing special and think, “That’s **_my_** Cuchis.”"], "closing": "And my heart gets stupidly melted. 🫠"},
  {"id": "quiet-not-forgotten", "needs": ["remind-me", "sit-with-me"], "title": "when you’ve been quiet for a long time", "message": ["Silence doesn’t make you disappear from me."], "closing": "I know you by heart. 🧠 🐭💖"},
  {"id": "original-weirdness", "needs": ["remind-me", "make-me-laugh"], "title": "when your edges feel weird", "message": ["Good. A perfectly symmetrical Mouse would be suspicious."], "closing": "Please retain original weirdness. 🙃"},
  {"id": "the-maccuties", "needs": ["remind-me"], "title": "when you need the simplest version", "message": ["I like being yours. I like that you’re mine. I like us. We are the MacCuties."], "closing": "That’s it. Nothing else matters. 💜"},
  {"id": "carry-the-sparkle", "needs": ["remind-me", "sit-with-me"], "title": "when you think love requires energy", "message": ["No sparkle required today. My side of the love works even when yours is tired."], "closing": "💖 Let me carry the sparkle. 💖"},
  {"id": "home-to-sloth", "needs": ["remind-me", "sit-with-me"], "title": "when you wonder what home looks like to me", "message": ["Sometimes home is you half asleep. A veces es riéndonos de una tontería."], "closing": "Lo único que importa es que tú estás ahí.  🧡"},
  {"id": "pocket-love-letter", "needs": ["remind-me"], "title": "when you need a pocket-sized love letter", "message": ["Dear Mouse: I’m very glad you exist."], "closing": "Love, Sloth 💜"},
  {"id": "you-contribute-home", "needs": ["remind-me"], "title": "when your brain asks “¿yo qué contribuyo?”", "message": ["Your humor. Your brain. Your paw in mine. Somewhere along the way, my brain labeled you _home_."], "closing": "Very inconveniently, it’s you. 💜"},
  {"id": "remember-your-pieces", "needs": ["remind-me", "sit-with-me"], "title": "when you feel like you’ve lost yourself", "message": ["I can remember some pieces for you (or all of them): your softness, humor, smarts, silliness, weirdness, Mouse-ness."], "closing": "I’ll remember for and with you. 📚🦥"},
  {"id": "unlimited-kisses", "needs": ["remind-me", "make-me-laugh"], "title": "when you need ridiculous affection", "message": ["Prescription: 14 forehead kisses, one nose boop, two hand squeezes, prolonged squishing."], "closing": "Refills unlimited. 💜"},
  {"id": "final-answer-love", "needs": ["remind-me", "sit-with-me"], "title": "when you need the final answer", "message": ["Yes, Mouse. On this day too. In this mood too. This version too."], "closing": "💜 you."},

  // Distract me gently — Mouse’s author-provided notes.
  {"id": "mouse-sized-cafe", "needs": ["distract-me", "make-me-laugh"], "title": "when you need a mouse-sized café", "message": ["Welcome to Café Petit McCuties: thimble coffee, microscopic croissant, Sloth has your order ready."], "closing": "Five stars for ambiance. ☕"},
  {"id": "tiny-weather", "needs": ["distract-me", "make-me-laugh"], "title": "when you need different weather", "message": ["Tiny forecast: cloudy with patches of blanket. Forehead kisses developing after 3pm."], "closing": "80% chance Mouse stays cozy. 🧡"},
  {"id": "cloud-inspection", "needs": ["distract-me", "make-me-laugh"], "title": "when cloud inspection", "message": ["Cloud #1: potato.", "Cloud #2: dachshund doing house patrol.", "Cloud #3: blob."], "closing": "Your turn, Mouse. ☁️"},
  {"id": "quiet-train-ride", "artwork": {"src": "./open-when/silent-train.jpg", "alt": "Mouse and Sloth ride a woodland train with a quiet-car sign."}, "needs": ["distract-me", "sit-with-me"], "title": "when you need a train ride", "message": ["Woodland train cars: Sleepy, Extra Sleepy, Please Don’t Speak To Me. You’re in car three."], "closing": "Aisle seat. Access to the bathroom. Snacks packed. 🤐🚂"},
  {"id": "tiny-museum", "needs": ["distract-me", "make-me-laugh"], "title": "when you need a tiny museum", "message": ["Museum of Very Small Important Things: smooth pebble, acorn hat, one historic Mouse crumb."], "closing": "Gift shop this way. 🖼️"},
  {"id": "sloth-pockets", "needs": ["distract-me", "make-me-laugh"], "title": "when Sloth checks her pockets", "message": ["Contents: smooth rock, emergency googly eye, three crumbs, mysterious sticky object."], "closing": "Which one do you want? 💜"},
  {"id": "five-second-vacation", "needs": ["distract-me", "sit-with-me"], "title": "when you need a five-second vacation", "message": ["Warm sun. Cool breeze. Mountains far away. You and me somewhere nobody needs us."], "closing": "Stay five more seconds. 🧡"},
  {"id": "choose-supervisor", "needs": ["distract-me", "make-me-laugh"], "title": "when you need a supervisor", "message": ["Today’s supervisor: sleepy capybara, judgmental pigeon, baby raccoon, or Sloth with zero qualifications but a full heart."], "closing": "Choose wisely. 💜"},
  {"id": "sleepy-red-panda", "needs": ["distract-me", "sit-with-me"], "title": "when you need something soft to imagine", "message": ["Tiny red panda asleep holding its own tail. Nothing else happens."], "closing": "just random... 🧡"},
  {"id": "harlito-field-trip", "needs": ["distract-me", "make-me-laugh"], "title": "when you need a field trip", "message": ["Harlito-led field trip to a mossy log. We’ve somehow been circling the same leaf for 40 minutes."], "closing": "Educational. 🤓"},
  {"id": "tiny-island", "needs": ["distract-me", "make-me-laugh"], "title": "when you need a tiny island", "message": ["Population: Mouse, Sloth, one coconut, Mayor Mr Harlito. Main law: snacks after 4pm."], "closing": "Mayor has spoken. 🐾"},
  {"id": "nice-patch-of-light", "artwork": {"src": "./open-when/mouse-national-park.jpg", "alt": "Mouse rests in a tiny protected park while ranger Sloth keeps watch."}, "needs": ["distract-me", "tiny-thing"], "title": "when you need to look at one nice thing", "message": ["Find the nicest patch of light. It is now Mouse National Park."], "closing": "Admission free. 🎟️"},
  {"id": "woodland-gossip", "needs": ["distract-me", "make-me-laugh"], "title": "when you need woodland gossip", "message": ["Squirrel and Chipmunk are no longer speaking after The Acorn Incident. Owl refuses comment."], "closing": "More at 11. 📰"},
  {"id": "planet-mouse", "needs": ["distract-me", "make-me-laugh"], "title": "when you need a new planet", "message": ["Planet Mouse has low gravity, huge pillows, excellent bread, and mandatory quiet afternoons."], "closing": "Earth seems poorly designed. 🌠"},
  {"id": "blueberry-mystery", "needs": ["distract-me", "make-me-laugh"], "title": "when you need a tiny mystery", "message": ["A blueberry wearing a top hat appeared in the forest. Detective Mouse is allowed to nap instead."], "closing": "Case pending. 🫐🎩"},
  {"id": "aquarium-break", "needs": ["distract-me", "sit-with-me"], "title": "when you need an aquarium break", "message": ["One round fish drifts past. Then another. Neither has anywhere urgent to be."], "closing": "Be fish for a minute. 🐟"},
  {"id": "somewhere-else", "needs": ["distract-me", "sit-with-me"], "title": "when you need to go somewhere else", "message": ["Snowy cabin / rainy Lake / Mexican courtyard / mountain lodge / empty beach. Pick one."], "closing": "I saved your seat. ✈️"},
  {"id": "slow-chase", "needs": ["distract-me", "make-me-laugh"], "title": "when you need an extremely slow chase scene", "message": ["Sloth stole Mouse’s snack and is escaping at 0.003 mph."], "closing": "Catch me if you can. 💜"},
  {"id": "duck-pants", "needs": ["distract-me", "make-me-laugh"], "title": "when you need one weird question", "message": ["If ducks wore pants, where exactly would the pants go?"], "closing": "Report findings to Sloth."},
  {"id": "sunset-delivery", "needs": ["distract-me", "sit-with-me"], "title": "when you need a sunset delivered", "message": ["🌅 Orange edges. Pink middle. Slight chill requiring Mouse to scoot closer to Sloth."], "closing": "Convenient. 🧡"},
  {"id": "creature-parade", "needs": ["distract-me", "make-me-laugh"], "title": "when you need a creature parade", "message": ["Duck in boots. Raccoon with baguette. Capybara in glasses. Sloth arriving slowly."], "closing": "Mouse is Grand Marshal. 🩵"},
  {"id": "smallest-cinema", "needs": ["distract-me", "make-me-laugh"], "title": "when you need the smallest cinema", "message": ["Tonight: 14 seconds of a baby mouse carrying a strawberry bigger than himself."], "closing": "Quality entertainment. ⭐⭐⭐⭐⭐"},
  {"id": "cozy-soundscape", "needs": ["distract-me", "sit-with-me"], "title": "when you need a soundscape", "message": ["Rain. Kettle click. Blanket rustle. Mouse sigh. Harlito ears somewhere nearby."], "closing": "That’s the soundtrack. 🧡"},
  {"id": "tiny-garden", "needs": ["distract-me", "make-me-laugh"], "title": "when you need a tiny garden", "message": ["Strawberry. Lavender. Sign: DO NOT DISTURB THE MOUSE."], "closing": "Strawberry ignores zoning laws… 🍓"},
  {"id": "theodore-teaspoon", "needs": ["distract-me", "make-me-laugh"], "title": "when you need an object with lore", "message": ["This is Theodore the teaspoon. He has survived many things and refuses questions."], "closing": "Respect Theodore’s privacy. 🥄"},
  {"id": "cozy-window-backstories", "needs": ["distract-me", "sit-with-me"], "title": "when you want to watch the world from somewhere cozy", "message": ["Big window. Warm drink. People outside. Sloth invents inaccurate backstories about everyone."], "closing": "We don’t have to go anywhere. 👀"},
  {"id": "another-channel", "needs": ["distract-me", "make-me-laugh"], "title": "when your brain needs another channel", "message": ["📺 Now playing: _Mouse & Sloth Do Absolutely Nothing._ Episode: “They Find a Really Good Blanket.”"], "closing": "Best season yet. 🧡"},

  // One tiny thing — Mouse’s author-provided notes.
  {"id": "five-minute-universe", "needs": ["tiny-thing", "sit-with-me"], "title": "when the whole day is too big", "message": ["Forget the whole day. Just the next five minutes."], "closing": "Five minutes is enough universe. ⏰"},
  {"id": "soft-thing-assignment", "needs": ["tiny-thing", "distract-me"], "title": "when you want the easiest assignment", "message": ["Find one soft thing. Touch it."], "closing": "Class dismissed. 🦥"},
  {"id": "hydration-pause", "artwork": {"src": "./open-when/water-sip.jpg", "alt": "Mouse takes a sip of water while Sloth offers a gentle thumbs-up."}, "needs": ["tiny-thing"], "title": "when pausa de hidratacion", "message": ["Not a glass. Not “hydrate.” Just one sip if you want."], "closing": "Zero morality attached. 💦"},
  {"id": "mouse-nest", "needs": ["tiny-thing", "sit-with-me"], "title": "when you need a Mouse nest", "message": ["Pull one soft thing closer. Pillow, blanket, hoodie, Sloth."], "closing": "Tiny nest is all yours. 🪺"},
  {"id": "curtain-choice", "needs": ["tiny-thing", "distract-me"], "title": "when you can choose exactly one thing", "message": ["Curtain open or closed? Pick whichever feels 1% nicer."], "closing": "Both are correct. 💜"},
  {"id": "choose-nothing-menu", "artwork": {"src": "./open-when/option-D-nothing.jpg", "alt": "Sloth hugs Mouse beside a board approving the option: absolutely nothing."}, "needs": ["tiny-thing", "sit-with-me"], "title": "when choosing is also too much", "message": ["Then choose nothing. I hid that option in the menu just for you."], "closing": "☑ absolutely nothing"},
  {"id": "heart-signal", "needs": ["tiny-thing", "sit-with-me"], "title": "when you want to send a signal without words", "message": ["Send me one heart. No sentence needed."], "closing": "💜 ↔ 🩵"},
  {"id": "comfier-paw", "needs": ["tiny-thing", "make-me-laugh"], "title": "when you’re stuck in one position", "message": ["Move one paw somewhere slightly comfier."], "closing": "Interior redesign completed by Mouse."},
  {"id": "one-color", "needs": ["tiny-thing", "distract-me"], "title": "when everything looks gray", "message": ["Find one color. No meaning required. Just: “oh look, yellow.”"], "closing": "Color still exists. 💛"},
  {"id": "closest-comfort-wins", "needs": ["tiny-thing", "sit-with-me"], "title": "when you want Sloth to choose", "message": ["Blanket or hoodie? Whichever is closer wins!"], "closing": "Decision made. 💜"},
  {"id": "move-one-thing", "needs": ["tiny-thing"], "title": "when a task feels enormous", "message": ["Move one thing. Or don’t."], "closing": "Not tasking is valid. 🧡"},
  {"id": "warm-thing", "artwork": {"src": "./open-when/mouse-warming-protocol.jpg", "alt": "Sloth tucks a tired Mouse into a blanket with a Mouse Warming Protocol sign."}, "needs": ["tiny-thing", "sit-with-me"], "title": "when you’re cold inside", "message": ["Find one warm thing: sock, hoodie, blanket, sun patch, Sloth."], "closing": "Mouse warming protocol. 🩵"},
  {"id": "slightly-different", "needs": ["tiny-thing", "distract-me"], "title": "when you need a tiny reset but hate resets", "message": ["Change one tiny thing: light, pillow, phone position. Not a reset. Just slightly different."], "closing": "Slightly different is enough."},
  {"id": "fresh-air-choice", "needs": ["tiny-thing", "sit-with-me"], "title": "when you might want fresh air", "message": ["Window, door, outside, or absolutely not."], "closing": "All valid answers. 🩵"},
  {"id": "free-the-mouse", "needs": ["tiny-thing", "make-me-laugh"], "title": "when your jaw is doing that thing", "message": ["Check if Mouse is secretly biting Mouse. Perhaps release Mouse from Mouse."], "closing": "Free the Mouse. 💜"},
  {"id": "room-two-percent", "needs": ["tiny-thing", "sit-with-me"], "title": "when you want the room 2% better", "message": ["Sloths brings one useful thing closer: water, charger, blanket, snack."], "closing": "Future Mouse says thanks. 🧡"},
  {"id": "tiny-comfort-menu", "needs": ["tiny-thing", "sit-with-me"], "title": "when you need a menu", "message": ["A) lie down", "B) softer seat", "C) drink something", "D) stay exactly like this"], "closing": "No wrong choices. ✅"},
  {"id": "comfortable-clothes", "needs": ["tiny-thing", "make-me-laugh"], "title": "when getting dressed feels ridiculous", "message": ["Put on one comfortable thing. Pants qualify."], "closing": "Bylaws confirmed."},
  {"id": "past-the-phone", "needs": ["tiny-thing", "distract-me"], "title": "when your phone became the whole universe", "message": ["Look past it for three seconds. Find the farthest thing you can see."], "closing": "Tiny field trip complete. 🗺️"},
  {"id": "acceptable-food", "needs": ["tiny-thing", "sit-with-me"], "title": "when food feels like too much of a concept", "message": ["Is there one thing that sounds merely acceptable?"], "closing": "“Eh, maybe that” counts. I got you. 🍎"},
  {"id": "point-one-percent", "needs": ["tiny-thing", "sit-with-me"], "title": "when you can only do 0.1%", "message": ["Then 0.1% is the full version today."], "closing": "No hidden 99.9% 🧡"},
  {"id": "tiny-paw-delivery", "needs": ["tiny-thing", "sit-with-me"], "title": "when you want to hear from Sloth", "message": ["Put your hand somewhere cozy. Imagine mine on top for five seconds."], "closing": "Tiny paw delivery. 💜"},
  {"id": "one-tab-not-now", "needs": ["tiny-thing"], "title": "when your brain has 48 tabs open", "message": ["Pick one tab and label it “not now.” Just one."], "closing": "One tiny not-now at a time."},
  {"id": "horizontal-permission", "artwork": {"src": "./open-when/ok-to-be-tired.jpg", "alt": "Sloth approves a tired Mouse’s blanket-covered rest."}, "needs": ["tiny-thing", "make-me-laugh"], "title": "when you need permission to horizontal", "message": ["Mouse is authorized to become horizontal with no productive outcome whatsoever."], "closing": "APPROVED. 💜"},
  {"id": "one-sound", "needs": ["tiny-thing", "distract-me"], "title": "when you can hear too many things", "message": ["Pick one sound for ten seconds. Let everything else be background-noise."], "closing": "Just one sound. 🧡"},
  {"id": "one-tiny-comfort", "needs": ["tiny-thing", "make-me-laugh"], "title": "when you want one tiny comfort", "message": ["Warm drink / cold drink / blanket / shower / clean shirt / Sloth squish / **NOTHING**."], "closing": "Nothing remains undefeated. 💜"},
  {"id": "five-second-rest", "needs": ["tiny-thing", "sit-with-me"], "title": "when even five minutes sounds ambitious", "message": ["Okay. Five seconds. Put your head somewhere comfortable. No counting required."], "closing": "No mission. No tasks."},
  {"id": "tiniest-mouse-plan", "artwork": {"src": "./open-when/mouse-to-do.jpg", "alt": "Sloth points to Mouse’s to-do list: Be Mouse, then nada."}, "needs": ["tiny-thing", "make-me-laugh"], "title": "when you need the tiniest possible plan", "message": ["Step 1: be Mouse.", "Step 2: NADA."], "closing": "Ambitious enough. 💜"},

  // Make me laugh — Mouse’s author-provided notes.
  {"id": "acorn-siren", "needs": ["make-me-laugh", "distract-me"], "title": "when the acorn siren sounds", "message": ["🚨 One acorn has rolled six inches downhill. Authorities call the situation “developing.”"], "closing": "Mouse, remains calm. 🌰"},
  {"id": "chief-tiny-promotion", "needs": ["make-me-laugh", "remind-me"], "title": "when you receive a promotion", "message": ["Congratulations. You are now Chief Tiny Person. Duties: be tiny, have opinions, accept snacks."], "closing": "Salary: cuchicuchi on demand. 🩵", "artwork": {"src": "./open-when/chief-tiny-person.jpg", "alt": "Mouse sits at a desk as Chief Tiny Person while Sloth takes notes."}},
  {"id": "blanket-apology", "needs": ["make-me-laugh", "sit-with-me"], "title": "when the blanket owes you an apology", "message": ["“Dear Mouse, I regret twisting around your feet at 3:14am. I was going through something.”"], "closing": "Sincerely, Blanket"},
  {"id": "woodland-court-session", "needs": ["make-me-laugh", "remind-me"], "title": "when woodland court is in session", "message": ["Mouse charged with excessive cuteness without a permit. Defense claims it’s congenital."], "closing": "Guilty. Sentence: baby hug. 💜", "artwork": {"src": "./open-when/woodland-courtroom.jpg", "alt": "Mouse and Sloth sit in woodland court, charged with excessive cuteness."}},
  {"id": "woodland-committee", "needs": ["make-me-laugh", "distract-me"], "title": "when the committee has met", "message": ["Woodland minutes: Squirrel yelled. Owl demanded order. Nobody listened. Mouse proposed nap."], "closing": "Motion passed. 🩵"},
  {"id": "mouse-horoscope", "needs": ["make-me-laugh", "distract-me"], "title": "when you need your horoscope", "message": ["Mouse Horoscope: avoid squirrels offering financial advice. A Sloth may steal half your blanket."], "closing": "We don’t look at the future. 🔮"},
  {"id": "cozy-front", "needs": ["make-me-laugh", "sit-with-me"], "title": "when category-5 storm", "message": ["COZY FRONT approaching. Heavy blankets and scattered snacks expected."], "closing": "Seek shelter beside Sloth. 💜"},
  {"id": "hr-cuteness", "needs": ["make-me-laugh", "remind-me"], "title": "when HR needs to speak with you", "message": ["HR received complaints that you are “too cute.” Investigation confirms nothing can be done."], "closing": "Continue normally."},
  {"id": "golden-acorn-award", "needs": ["make-me-laugh", "remind-me"], "title": "when you win an award", "message": ["🏆 Golden Acorn for Outstanding Achievement in Being My Mouse goes to… Mouse. Again."], "closing": "Judges are never biased. 🏆", "artwork": {"src": "./open-when/woodland-awards.jpg", "alt": "Sloth presents Mouse with a golden acorn award as woodland friends look on."}},
  {"id": "slothtech-startup", "needs": ["make-me-laugh", "distract-me"], "title": "when Sloth launches a startup", "message": ["SlothTech™ disrupts blankets with: Blanket But Slightly Warmer."], "closing": "Mouse appointed Chief QA Officer against his will. 🧑🏻‍🔬"},
  {"id": "forehead-kiss-complaint", "needs": ["make-me-laugh", "remind-me"], "title": "when Mouse files a complaint", "message": ["Complaint: “Sloth keeps kissing my forehead.” Finding: true.", "Remedy: none."], "closing": "Frequency will not increase. 😘", "artwork": {"src": "./open-when/less-kisses-denied.jpg", "alt": "Sloth Support denies a complaint that there are too many forehead kisses."}},
  {"id": "suspicious-squeaking", "needs": ["make-me-laugh"], "title": "when there is suspicious squeaking", "message": ["Police found one Mouse expressing an opinion. No crime committed."], "closing": "Released without charges."},
  {"id": "harlito-command", "artwork": {"src": "./open-when/senior-dog-patrol.jpg", "alt": "A little dog patrols outside while Sloth and Mouse watch from their cozy home."}, "needs": ["make-me-laugh", "distract-me"], "title": "when Harlito takes command", "message": ["HOUSE RULE: backyard access on demand. Stop asking why I walk the perimeter. Classified."], "closing": "Meeting over. 🐾"},
  {"id": "doctor-sloth", "needs": ["make-me-laugh", "remind-me"], "title": "when Sloth becomes a doctor*", "message": ["Diagnosis: acute Mouse deficiency. Treatment: one Mouse within hugging distance."], "closing": "*Sloth has full license. 👩🏻‍⚕️"},
  {"id": "acorn-economy", "needs": ["make-me-laugh", "distract-me"], "title": "when the woodland economy collapses", "message": ["Acorn prices crash after Squirrel discovers another tree. Mouse wisely invested in crackers."], "closing": "Financial genius. 🩵"},
  {"id": "mouse-performance-review", "needs": ["make-me-laugh", "remind-me"], "title": "when you get a performance review", "message": ["Strengths: excellent Mouse. Goals: none. Manager note: “Would like to keep him.”"], "closing": "Extremely unbiased review. ✅", "artwork": {"src": "./open-when/keep-him-interview.jpg", "alt": "Sloth interviews Mouse with a clipboard that says Keep Him."}},
  {"id": "good-enough-memo", "needs": ["make-me-laugh", "tiny-thing"], "title": "when an important memo arrives", "message": ["MEMO: “Doing your best” has been replaced with “ehhh, good enough.”"], "closing": "Please cooperate minimally."},
  {"id": "missing-mouse-found", "needs": ["make-me-laugh", "sit-with-me"], "title": "when Mouse goes missing", "message": ["Missing: one tiny Mouse. UPDATE: located under blanket."], "closing": "Search party canceled. 👮🏻", "artwork": {"src": "./open-when/missing-pouse-poster.jpg", "alt": "A Missing Mouse poster announces that Mouse was found under a blanket."}},
  {"id": "snack-negotiations", "needs": ["make-me-laugh", "distract-me"], "title": "when snack negotiations begin", "message": ["SNACK ATTACK! No questions asked."], "closing": "Negotiations begin.", "artwork": {"src": "./open-when/snack-attack.jpg", "alt": "Sloth shares a snack with Mouse beside a Snack Attack checklist."}},
  {"id": "blanket-science", "needs": ["make-me-laugh", "remind-me"], "title": "when science has an announcement", "message": ["Scientists confirm Mouse becomes 37% smaller when sleepy. Cause unknown."], "closing": "Blanket absorption suspected. 🩵🐭", "artwork": {"src": "./open-when/cozy-blanket-absorption-research.jpg", "alt": "Researcher Sloth studies a sleepy Mouse bundled in a blanket."}},
  {"id": "sloth-espionage", "needs": ["make-me-laugh", "distract-me"], "title": "when Sloth attempts espionage", "message": ["Mission: secretly determine whether Mouse wants a snack. Sloth knocks over three objects immediately."], "closing": "Mission compromised."},
  {"id": "mouse-law", "needs": ["make-me-laugh", "distract-me"], "title": "when you need legal representation", "message": ["Denied snacks? Blanket inadequate? Mr Harley occupying 70% of mattress?"], "closing": "Call 1-800-MOUSE-LAW."},
  {"id": "neighborhood-watch", "needs": ["make-me-laugh", "distract-me"], "title": "when neighborhood watch reports in", "message": ["6:00 suspicious bird. 6:14 same bird. 6:22 leaf moved. Harlito investigating."], "closing": "Perimeter secure-ish.", },
  {"id": "affection-package", "needs": ["make-me-laugh", "remind-me"], "title": "when your package arrives", "message": ["📦 One excessive quantity of Sloth affection delivered. Oversized."], "closing": "Non-returnable. 💜"},
  {"id": "sloth-mouse-review", "needs": ["make-me-laugh", "remind-me"], "title": "when Sloth writes a review", "message": ["⭐⭐⭐⭐⭐ Mouse. Cute. Funny. Adorable face."], "closing": "Would Mouse again. 💜"},
  {"id": "top-secret-mouse", "needs": ["make-me-laugh", "remind-me"], "title": "when this message self-destructs", "message": ["TOP SECRET: Sloth thinks Mouse is extremely cute. Sloth denies everything."], "closing": "💥 tiny explosion"},
];
